global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'product-comparison-monitor'

# Alert rules
rule_files:
  - '/etc/prometheus/alerts.yml'

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Aplicación Go (si exporta métricas en /metrics)
  - job_name: 'product-comparison-api'
    static_configs:
      - targets: ['product-comparison-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # cAdvisor - Métricas de contenedores Docker
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s

  # Loki
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

